version: '3.9'

services:
  arc-backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - '../:/app'
      - '../node_modules:/app/node_modules'
    ports:
      - 4000:4000
    env_file:
      ../.env
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ../db:/data/db:delegated
